import groovy.json.JsonOutput

def do_test = false

pipeline {
    agent {
        label 'run-unittest'
    }

    stages {
        stage('Cleanup') {
            steps {
                script {
                    message = "An unit test has been triggered on ${env.BUILD_URL}"
                    review_data = JsonOutput.toJson([message: message])
                    writeFile file: "data.json", text: review_data
                    sh "cat data.json| ssh mysoyul.park@${env.GERRIT_HOST} gerrit review ${env.GERRIT_CHANGE_NUMBER},${env.GERRIT_PATCHSET_NUMBER} --json"
                    echo "Remove 'module' directory"
                    sh "sudo rm -rf module"
                    currentBuild.description = "<li>${env.GERRIT_PROJECT}</li><li>${env.GERRIT_CHANGE_NUMBER},${env.GERRIT_PATCHSET_NUMBER}</li><li>${env.GERRIT_EVENT_ACCOUNT_NAME}</li>"
                }
            }
        }
        stage('Checkout a change') {
            steps {
                script {
                    echo "Checkout a change from Gerrit"
                    sh "git clone ssh://${env.GERRIT_HOST}/${env.GERRIT_PROJECT} module 2>&1"
                    sh "cd module && git fetch origin ${env.GERRIT_REFSPEC} && git checkout FETCH_HEAD"
                    if (fileExists("module/run-test.sh") && fileExists("module/docker-compose.yml")) {
                        do_test = true
                    }
                    def comment_base64 = env.GERRIT_EVENT_COMMENT_TEXT
                    def comment = new String(comment_base64.decodeBase64())
                    echo "DEBUG: ${comment}"
                }
            }
        }
        stage('Trigger Unit Test') {
            when {
                expression { return do_test }
            }
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'lge_ad', passwordVariable: 'LGE_AD_PASSWORD', usernameVariable: 'LGE_AD_USERNAME')]){
                        sh "docker login -u ${LGE_AD_USERNAME} -p ${LGE_AD_PASSWORD} ${LGE_DOCKER_REGISTRY_HOST} && cd module && docker-compose pull && docker-compose run run-test 2>&1"
                    }
                }
            }
        }
    }
    post {
        success {
            script {
                def review_message = ""
                def verified = "0"
                if (do_test) {
                    review_message = "Success: Unit Test on ${env.BUILD_URL}"
                    verified = "1"
                } else {
                    review_message = "Your change doesn't have run-test.sh and docker-compose.yml files on the root. So you can't use Unit test enviroments"
                }
                review_data = JsonOutput.toJson([message: review_message, labels: [Verified: verified]])
                writeFile file: "data.json", text: review_data
                sh "cat data.json | ssh mysoyul.park@${env.GERRIT_HOST} gerrit review ${env.GERRIT_CHANGE_NUMBER},${env.GERRIT_PATCHSET_NUMBER} --json"
            }
        }
        failure {
            script {
                def review_message = "Failure: Unit test on ${env.BUILD_URL}"
                def verified = "-1"
                review_data = JsonOutput.toJson([message: review_message, labels: [Verified: verified]])
                writeFile file: "data.json", text: review_data
                sh "cat data.json | ssh mysoyul.park@${env.GERRIT_HOST} gerrit review ${env.GERRIT_CHANGE_NUMBER},${env.GERRIT_PATCHSET_NUMBER} --json"
            }
        }
    }
}
